### Combine Citi Bike Trip History Logs

In [15]:
import pandas as pd
import os
import glob
import numpy as np
import datetime

In [16]:
#Read the path where the Citi Bike Trip History Logs are.
cwd = os.path.abspath('')

In [17]:
#list all csv files from the Directory same as where the 
All_Trip_History_log_files = glob.glob('*.{}'.format('csv'))
All_Trip_History_log_files

['JC-202203-citibike-tripdata.csv',
 'JC-202201-citibike-tripdata.csv',
 'JC-202111-citibike-tripdata.csv',
 'JC-202107-citibike-tripdata.csv',
 'JC-202109-citibike-tripdata.csv',
 'JC-202205-citibike-tripdata.csv',
 'JC-202112-citibike-tripdata.csv',
 'JC-202202-citibike-tripdata.csv',
 'JC-202110-citibike-tripdata.csv',
 'JC-202206-citibike-tripdata.csv',
 'JC-202108-citibike-tripdata.csv',
 'JC-202204-citibike-tripdata.csv']

In [18]:
#Combine all .csv files into a Data Frame.

Combined_df = pd.concat([pd.read_csv(f) for f in All_Trip_History_log_files], ignore_index=True)
Combined_df.head(5)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,3255D3E3F33CDC45,classic_bike,2022-03-18 15:38:17,2022-03-18 15:45:34,Mama Johnson Field - 4 St & Jackson St,HB404,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,40.743140,-74.040041,40.736982,-74.027781,casual
1,17FA5604A37338F9,electric_bike,2022-03-04 16:44:48,2022-03-04 16:50:45,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member
2,7DEC9ADDB8D6BBE1,electric_bike,2022-03-13 17:44:32,2022-03-13 17:54:44,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member
3,9D69F74EEF231A2E,classic_bike,2022-03-13 15:33:47,2022-03-13 15:41:22,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member
4,C84AE4A9D78A6347,classic_bike,2022-03-11 12:21:18,2022-03-11 12:33:24,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member

In [19]:
# Convert All DateTimes to "%Y-%m-%d %H:%M:%S" Format
Combined_df[["started_at","ended_at"]] = Combined_df[["started_at","ended_at"]].apply(pd.to_datetime)
Combined_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,3255D3E3F33CDC45,classic_bike,2022-03-18 15:38:17,2022-03-18 15:45:34,Mama Johnson Field - 4 St & Jackson St,HB404,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,40.743140,-74.040041,40.736982,-74.027781,casual
1,17FA5604A37338F9,electric_bike,2022-03-04 16:44:48,2022-03-04 16:50:45,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member
2,7DEC9ADDB8D6BBE1,electric_bike,2022-03-13 17:44:32,2022-03-13 17:54:44,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member
3,9D69F74EEF231A2E,classic_bike,2022-03-13 15:33:47,2022-03-13 15:41:22,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member
4,C84AE4A9D78A6347,classic_bike,2022-03-11 12:21:18,2022-03-11 12:33:24,Baldwin at Montgomery,JC020,Grove St PATH,JC005,40.723659,-74.064194,40.719586,-74.043117,member

In [22]:
#Adding columns for trip duration and calculated in hours,minutes, and seconds.
Combined_df['Trip_duration_hours'] = (Combined_df.ended_at - Combined_df.started_at)/pd.Timedelta(hours=1)
Combined_df['Trip_duration_minutes'] = (Combined_df.ended_at - Combined_df.started_at)/pd.Timedelta(minutes=1)
Combined_df['Trip_duration_seconds'] = (Combined_df.ended_at - Combined_df.started_at)/pd.Timedelta(seconds=1)
Combined_df['Trip_duration_seconds'].nlargest(n=2)

171036    11221289.0
106199     5273333.0
Name: Trip_duration_seconds, dtype: float64

In [21]:
#Exporting combined data file to the main data folder.

Combined_df.to_csv('/Users/KM/Desktop/Homework_Completed/20.Tableau Homework _Citi Bike Analytics/Trip_History_Logs/Combined_Trip_History_data_log.csv');